enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk appparallel-jobs = 1


[YouTube-ReVanced-Extended]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "YouTube"
