enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Custom header for YouTube' 'MaterialYou'"
patcher-args = "-OcustomHeader=Aurora -OappName=YouTube Extended "
