enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk appparallel-jobs = 1


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
